# Generated by Django 5.2.15 on 2026-07-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_memberpremiumfeature_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='planfeaturepermission',
            name='allowed_operations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='memberpremiumfeature',
            name='category',
            field=models.CharField(choices=[('matrimony', 'Matrimony'), ('messaging', 'Messaging'), ('business', 'Business'), ('jobs', 'Jobs'), ('events', 'Events'), ('property', 'Property Booking'), ('directory', 'Directory'), ('profile', 'Profile'), ('ai', 'AI Features'), ('marketplace', 'Marketplace'), ('support', 'Support'), ('donations', 'Donations'), ('ads', 'Advertisements'), ('committee', 'Committee'), ('attendance', 'Attendance'), ('subsidiaries', 'Subsidiaries'), ('venues', 'Venues'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='ModulePermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_definitions', to='api.featuremaster')),
            ],
            options={
                'unique_together': {('feature', 'code')},
            },
        ),
    ]
