# Generated by Django 5.2.15 on 2026-07-03 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_planfeaturepermission_allowed_operations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='planaddon',
            old_name='limit_value',
            new_name='increment',
        ),
        migrations.RemoveField(
            model_name='planaddon',
            name='limit_type',
        ),
        migrations.AddField(
            model_name='planaddon',
            name='category',
            field=models.CharField(default='Core', max_length=100),
        ),
        migrations.AddField(
            model_name='planaddon',
            name='compatible_plans',
            field=models.ManyToManyField(blank=True, related_name='addons', to='api.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='planaddon',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planaddon',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='planaddon',
            name='target_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='api.systemquota'),
        ),
    ]
