# Generated by Django 5.2.15 on 2026-09-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_systemquota_rename_limit_value_planaddon_increment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(default='PDF', max_length=50)),
                ('file_size', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(default='General Notice', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(default='General', max_length=100)),
                ('views_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.community')),
            ],
        ),
    ]
